#!/usr/bin/env bash
# This script installs nginx web server in a new Ubuntu machine,
# it also sets the configuration files accordingly.

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
