#!/usr/bin/env bash
# This script installs nginx web server in a new Ubuntu machine,
# it also sets the configuration files accordingly.
sudo apt-get update -y
sudo apt-get install nginx -y 
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
