#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine o that its HTTP response contains a custom header: X-Served-By
hostname=$(hostname)
string="\n\tadd_header X-Served-By \"$hostname\";"
sudo sed -i "/server_name _;/ a\\
$string" /etc/nginx/sites-available/default
sudo service nginx restart
