#!/usr/bin/env bash
# Install HAProxy
sudo apt-get update
sudo apt install -y haproxy 

# Starting on boot
echo "ENABLED=1" > /etc/default/haproxy
sudo systemctl enable haproxy

# Listen to web1 and web2 servers
echo "
frontend http_front
	bind *:80
	default_backend http_back

backend http_back
    balance roundrobin
    server 514072-web-01 100.27.11.128:80 check
    server 514072-web-02 54.209.192.180:80 check
" >> /etc/haproxy/haproxy.cfg 

# Restart HAProxy service
sudo service haproxy start
