#!/usr/bin/env bash
# This script configures you lb-01 server
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y
string="frontend myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend myservers\nbackend myservers\n\tbalance roundrobin\n\tmode http\n\tserver 514072-web-01 100.27.11.128:80 check\n\tserver 514072-web-02 54.209.192.180:80 check"
sudo sed -i "$ a $string" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
