#!/usr/bin/env bash
sudo apt-get install -y software-properties-common
sudo add-apt repository -y -ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy
# Listen to web1 and web2 servers
echo "
	listen load_balancer
	bind *:80
	mode http
    balance roundrobin
	option httpclose
	option forwardfor
    server 514072-web-01 100.27.11.128:80 check
    server 514072-web-02 54.209.192.180:80 check
" >> /etc/haproxy/haproxy.cfg 

 # Restart HAProxy service
 sudo service haproxy start
