#!/usr/bin/env bash
# configures an NGINX server to listen to port 80

sudo rm /etc/nginx/sites-enabled/*
sudo ln -s --force /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
