#!/usr/bin/env bash
# -configures an NGINX server to listen to port 80
ln -s --force /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"
