#!/usr/bin/env bash
# This script displays the PID, along w/ the process name, for processess whose name contain the word bash
list="$(pgrep bash)"
for i in $list
do
   echo "$i bash"
done
echo "$$ bash"
