#!/usr/bin/env bash
# This script Indefinitely writes I am alive! to the file /tmp/my_process In between every I am alive! message, the program should pause for 2 seconds
while true
do
   echo "I am alive!"
   sleep 2
done > /tmp/my_process
