#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

sed -n '11,$p' /etc/passwd | while IFS=: read -r user pass id group info home shell
do
   echo "The user $user is part of the $group gang, lives in $home and rides $shell. $id's place is protected by the passcode $pass, more info about the user here: $info"
done
