#!/usr/bin/env bash
# This script groups visotros by IP and HTTP  status code and dispalys the data
awk '{print $1,$9}' apache-access.log | awk '{count[$0]++}END{for (key in count) print count[key], key}' | sort -r -n 
