#!/usr/bin/env bash
# This script blocks all incoming traffic, except 22, 443, 80 TCP ports.
sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw allow 22 && sudo ufw allow 443 && sudo ufw allow 80
sudo ufw enable
