#!/usr/bin/env bash
# This script changes the owner of the nginx process to be the user nginx
pkill apache 
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/# user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
